#!/usr/bin/env bash
# forge-init.sh — scaffold the forge/ project convention into the current directory.
#
# Creates forge/ with the canonical layout described in
# plugins/forge/docs/project-conventions.md:
#   - forge/.gitignore          (committed, self-documenting policy)
#   - forge/README.md           (committed, points at the conventions doc)
#   - forge/hints/              (committed dir; only forge artifact in version control)
#   - forge/hints/README.md     (gitignored, local guidance for authoring hints)
#
# Idempotent: existing files are preserved. Re-running is safe — it fills in
# anything missing without overwriting customizations.
#
# Usage:
#   forge-init.sh [target-dir]
#
# Defaults to PWD when no arg given.

set -euo pipefail

TARGET_DIR="${1:-$PWD}"

if [ ! -d "$TARGET_DIR" ]; then
  echo "forge-init: target directory does not exist: $TARGET_DIR" >&2
  exit 1
fi

FORGE_DIR="$TARGET_DIR/forge"
HINTS_DIR="$FORGE_DIR/hints"

CREATED=()
SKIPPED=()

mkdir -p "$FORGE_DIR" "$HINTS_DIR"

# forge/.gitignore — self-documenting policy
GITIGNORE="$FORGE_DIR/.gitignore"
if [ ! -e "$GITIGNORE" ]; then
  cat > "$GITIGNORE" <<'EOF'
# By default, everything in this directory is local to your machine.
# Snippets, specs pending review, videos, pool state, transcripts — these
# are working artifacts you build up as you use forge, not things every
# teammate needs in the repo.
#
# Hints are the exception: they describe project-specific knowledge that
# every contributor needs (env contract, provisioning recipes, etc.).
#
# If your project has additional artifacts that should be shared (e.g.
# specific snippets you've curated and want everyone to use), add a
# `!path/` line below.

*
!.gitignore
!README.md
!hints/
!hints/**
!playwright.config.ts

# The hints/ README.md is scaffold-only — local guidance for authoring hints,
# not project-specific knowledge. Each user gets a fresh copy from /forge-init.
hints/README.md
EOF
  CREATED+=("forge/.gitignore")
else
  SKIPPED+=("forge/.gitignore")
fi

# forge/README.md — committed, points at the conventions doc
README="$FORGE_DIR/README.md"
if [ ! -e "$README" ]; then
  cat > "$README" <<'EOF'
# forge/

This directory holds forge artifacts for this project.

Only `hints/` is committed. Everything else (snippets, specs, videos, pool
state, transcripts) is local to your machine — see `.gitignore` for the
policy.

Hints are project-specific knowledge that every contributor needs: env
contract, provisioning recipes, app structure, conventions. See
`hints/README.md` (your local copy, gitignored) for guidance on authoring
them, or the full convention doc in the forge plugin source at
`plugins/forge/docs/project-conventions.md`.

## Quick reference

| File                  | Consumer                | Typical content                                  |
|-----------------------|-------------------------|--------------------------------------------------|
| `hints/forge.md`      | `/forge` skill          | env contract, provisioning recipe, env loading   |
| `hints/driver.md`     | `forge:driver` agent    | app structure, routes, personas, gotchas         |
| `hints/author.md`     | `forge:author` agent    | snippet conventions for this project             |
| `hints/spec-writer.md`| `forge:spec-writer` agent | spec conventions, naming, required imports     |
| `hints/verifier.md`   | `forge:verifier` agent  | how to verify specs, reset patterns              |

Minimum-viable hint files are very small. Forge has sensible defaults for
everything; hints encode only project-specific deviations.
EOF
  CREATED+=("forge/README.md")
else
  SKIPPED+=("forge/README.md")
fi

# forge/hints/README.md — gitignored, local hint authoring guidance
HINTS_README="$HINTS_DIR/README.md"
if [ ! -e "$HINTS_README" ]; then
  cat > "$HINTS_README" <<'EOF'
# Authoring hints

This README is gitignored — it's local scaffold material, regenerated by
`/forge-init`. Don't put project-specific knowledge here; that belongs in
the per-consumer hint files alongside this README.

## File-per-consumer convention

Each hint file is named after the agent or skill that reads it. Forge looks
for files matching these specific names:

- `forge.md`       — read by the `/forge` (or `/forge-team`) skill
- `driver.md`      — read by `forge:driver`
- `author.md`      — read by `forge:author`
- `spec-writer.md` — read by `forge:spec-writer`
- `verifier.md`    — read by `forge:verifier`

You don't have to author all of them. Forge has defaults for everything;
hint files override or augment those defaults for this specific project.

## What each file typically contains

### `forge.md` (skill-level orchestration)

Most projects start here. Declares:
- **Env contract** — which env keys each pool slot needs (e.g. `PORTAL_USERNAME`,
  `PORTAL_PASSWORD`, or `TENANT_ID`, or feature flag overrides — anything
  that varies per slot).
- **Env loading approach** — how the slot's env gets onto the subprocess.
  For direnv users: "each slot has a `.envrc`; wrap commands with
  `direnv exec <slot-dir>`." For plain-dotenv: "each slot has a `.env`;
  source it before invoking commands." For sops: see the conventions doc.
- **Provisioning recipe** — how to mint a new slot when the pool is
  exhausted. For apps with a fixed set of test users: pick one from this
  list. For apps where users can be created on-demand: an SQL insert + scaffold
  steps. The recipe runs without human help once authored.
- **Release cleanup** (optional) — anything project-specific that should
  happen when a slot is returned to the pool, beyond the default cookie
  and localStorage wipe.

### `driver.md` (browser navigation knowledge)

What the driver agent needs to know about *this specific app*:
- Common routes / URL patterns
- App structure (this is a planner with these tabs / this is an e-commerce
  with these flows / etc.)
- Available test users or personas
- Known gotchas — UI quirks, timing issues, things that look broken but
  aren't, anything the driver should be told upfront.

### `author.md`, `spec-writer.md`, `verifier.md`

Usually quite small. Project-specific exceptions to the universal forge
defaults that ship with the agents. For example:
- "Our checkout flow can take 30s on slow CI; allow longer waits."
- "Specs in this project name themselves `<feature>-<scenario>.spec.ts`."

If you don't have any deviations, don't author the file. Defaults apply.

## Tips

- Keep hints **declarative**, not procedural. "Use direnv exec to load env"
  is better than "first cd into the slot dir, then run direnv allow, then..."
  The skill knows how to apply a declared pattern.
- Don't put credentials in hints. Hints are committed. Slot env files (`.env` /
  `.envrc` / etc.) are gitignored — that's where secrets live, scoped per slot.
- Don't repeat what's already covered by forge defaults. The agent prompts
  enforce things like "snippets are idempotent" and "specs are E2E from
  login" automatically. Only mention them in your hint if your project
  needs to override them.

## See also

- `plugins/forge/docs/project-conventions.md` in the forge plugin source —
  full convention details and rationale.
EOF
  CREATED+=("forge/hints/README.md")
else
  SKIPPED+=("forge/hints/README.md")
fi

# forge/playwright.config.ts — committed, fallback config for forge specs
# when the project doesn't have a root-level Playwright runner.
PW_CONFIG="$FORGE_DIR/playwright.config.ts"
if [ ! -e "$PW_CONFIG" ]; then
  cat > "$PW_CONFIG" <<'EOF'
// Fallback Playwright config for forge specs in this project.
//
// Read by forge-pool-run-spec.mjs (and by Stage 4's verifier) when the
// project has no root-level playwright.config.{ts,js,mjs}. If your project
// has its own runner — e.g. e2e-tests/playwright.config.ts with custom
// fixtures, globalSetup, baseURL, etc. — forge-pool-run-spec.mjs will
// detect and prefer that config; this file is then unused and can stay
// as-is.
//
// Env loading (highest-precedence wins, last writer when non-override):
//
//   1. Process env at config-load time — your shell env, including anything
//      direnv (or another loader) put there. Always wins.
//   2. Slot env from `<slot>/.env` — injected by the forge wrapper scripts
//      via spawn when invoked with --slot. Already in process.env by the
//      time this config loads.
//   3. `forge/.env` — optional, for forge-specific overrides (e.g. different
//      baseURL or timeout for forge specs only, without touching project-
//      wide config). Loaded first below so it wins over project root .env.
//   4. `<project-root>/.env` — project baseline. Lowest precedence; only
//      fills in keys nothing above already set.
//
// dotenv's `override: false` default means values already in process.env
// are preserved — so #1 and #2 take precedence over #3 and #4 automatically.
// The keys you need are declared in your project's forge/hints/forge.md.
//
// Customize this when you DO want forge specs to use a config but don't
// want a project-wide one. Common additions:
//   - globalSetup: './global-setup.ts'      // e.g. clear DB before tests
//   - globalTeardown: './global-teardown.ts'
//   - use.baseURL: 'https://your.app/'
//   - reporter: [['list'], ['html']]
//   - timeout: 60_000
//
// Committed to the repo so teammates pick up the same fallback config.
import { defineConfig } from '@playwright/test'
import { config as loadEnv } from 'dotenv'
import { resolve } from 'node:path'

// Playwright's config loader compiles .ts files as CJS, so __dirname is
// injected automatically. We declare it to satisfy TypeScript without
// pulling in @types/node as a dep just for this.
declare const __dirname: string

// Load forge/.env first (forge-specific overrides), then project root .env
// (baseline). dotenv non-override means forge/.env wins over project/.env
// for any key they both define.
loadEnv({ path: resolve(__dirname, '.env') })
loadEnv({ path: resolve(__dirname, '..', '.env') })

export default defineConfig({
  testDir: './specs',
  fullyParallel: false,
  workers: 1,
  reporter: 'list',
})
EOF
  CREATED+=("forge/playwright.config.ts")
else
  SKIPPED+=("forge/playwright.config.ts")
fi

# Report
echo "forge-init: scaffolded $FORGE_DIR"
if [ ${#CREATED[@]} -gt 0 ]; then
  echo "  Created:"
  for f in "${CREATED[@]}"; do
    echo "    + $f"
  done
fi
if [ ${#SKIPPED[@]} -gt 0 ]; then
  echo "  Preserved (already present):"
  for f in "${SKIPPED[@]}"; do
    echo "    = $f"
  done
fi
echo ""
echo "Next: author hint files in $HINTS_DIR/ to describe your project's"
echo "env contract, provisioning recipe, and any project-specific conventions."
echo "See $HINTS_DIR/README.md for guidance."
